general.import = ["~/.config/alacritty/colors.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 18.0

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
padding = {x = 0, y = 0}
